### ISSUE TITLE
Can logs be rotated using this bundle?

### ISSUE THREAD

**Issue by reypm** [EasyCorp/easy-log-handler#8]
I am wondering if is there any way to [rotate logs](http://symfony.com/doc/current/logging.html#how-to-rotate-your-log-files) when I am using this bundle since I'd to get rid of the default config .... maybe this isn't necessary but was the only way to make it work. This is how my setup looks like:

```
 monolog:
    handlers:
        #main:
        #    type: stream
        #    path: "%kernel.logs_dir%/%kernel.environment%.log"
        #    level: debug
        #    channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        buffered:
            type:     buffer
            handler:  easylog
            channels: ["!event"]
            level:    debug
        easylog:
            type: service
            id:   easycorp.easylog.handler
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info
```

Can I rotate logs? How?
